---
x-airflow-common:
  &airflow-common
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
    # for other purpose (development, test and especially production usage) build/extend Airflow image.
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    &airflow-common-volumes
    - ${AIRFLOW_PROJ_DIR:-./airflow}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-./airflow}/logs:/opt/airflow/logs
    # - ${AIRFLOW_PROJ_DIR:-./airflow}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-./airflow}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-./airflow}/init_connection.py:/opt/airflow/init_connection.py
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

networks:
  docker-net:
    driver: bridge
    name: docker-net

volumes:
  postgres-airflow:
  traffic-redis-volume:
  kafka_data1:
  clickhouse:
  clickhouse_logs: 
  minio-volume:
  minio-config:
  # druid_data:

services:
  model-api:
    # build:
    #   context: ./model_service
    # image: traffic-api:latest
    image: phonghuynh/model-service:1.0.1
    hostname: object-counting-api
    container_name: object_counting_api
    ports:
      - "8000:8000"
    volumes:
      - ./model_service:/usr/src/app
    env_file:
      - .env
    networks:
      - docker-net
  
  # ui:
  #   build:
  #     context: ./appUI
  #   hostname: gradiou_ui
  #   container_name: gradio_ui
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./appUI:/usr/src/app
  #   env_file:
  #     - .env
  #   networks:
  #     - docker-net
  #   depends_on:
  #     - master-server
    
  postgres:
    image: postgres:13
    container_name: postgresdb
    hostname: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_CRAWL_DB: raw_crawl
      POSTGRES_CRAWL_USER: airflow_crawl
    volumes:
      - postgres-airflow:/var/lib/postgresql/data
      - ./database_init/psql_init/psql_init.sql:/docker-entrypoint-initdb.d/psql_init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - "5432:5432"
    networks:
      - docker-net


  airflow-webserver:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
      args:
        AIRFLOW_IMAGE_NAME: apache/airflow:2.10.5-python3.9
        AIRFLOW_UID: "${UID:-1000}"
    environment:
      <<: *airflow-common-env
      AIRFLOW_UID: ${AIRFLOW_UID:-1000}
    env_file:
      - .env
    image: &AIRFLOW_IMAGE traffic-airflow:2.10.5
    container_name: airflow-webserver
    <<: *airflow-common
    command: webserver
    # command: airflow api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - docker-net


  airflow-scheduler:
    image: *AIRFLOW_IMAGE
    container_name: airflow-scheduler
    <<: *airflow-common
    command: bash -c "python /opt/airflow/init_connection.py && airflow scheduler"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    env_file:
      - .env
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - docker-net


  airflow-triggerer:
    image: *AIRFLOW_IMAGE
    container_name: airflow-triggerer
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - docker-net


  airflow-init:
    image: *AIRFLOW_IMAGE
    container_name: airflow-init
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_USER_USERNAME:-root}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_USER_PASSWORD:-root}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-./airflow}:/sources
    networks:
      - docker-net

  airflow-cli:
    image: *AIRFLOW_IMAGE
    container_name: airflow-cli
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow
    networks:
      - docker-net
  

  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    restart: always
    volumes:
      - minio-volume:/data
      - minio-config:/root/.minio
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123}
      - AWS_REGION=us-east-1
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - docker-net

  minio-client:
    image: minio/mc
    container_name: minio-client
    hostname: mc
    restart: on-failure
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=minio:9000
      - DATALAKE_BUCKET=datalake
      # - MINIO_ROOT_USER=minio
      # - MINIO_ROOT_PASSWORD=minio123
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      until (/usr/bin/mc alias set minio http://minio:9000 ${MINIO_ROOT_USER:-minio} ${MINIO_ROOT_PASSWORD:-minio123}); 
      do echo '...waiting...' && sleep 2; done;
      echo 'MinIO is ready!';
      /usr/bin/mc mb minio/${DATALAKE_BUCKET:-datalake};
      /usr/bin/mc policy set public minio/${DATALAKE_BUCKET:-datalake};
      exit 0;
      "
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - docker-net


  redis:
    container_name: traffic-redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - docker-net
    volumes:
      - traffic-redis-volume:/data
  
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000" # TCP (for clickhouse-client cli)
    volumes:
      - clickhouse:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server/
      - ./database_init/clickhouse_init/clickhouse_init.sql:/docker-entrypoint-initdb.d/clickhouse_init.sql
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=user
      - CLICKHOUSE_DB=traffic_flow
    env_file:
      - .env
    networks:
      - docker-net 

  # druid:
  #   build:
  #     context: ./druid
  #   image: traffic-druid:latest
  #   hostname: druid
  #   ports:
  #     - "8888:8888"
  #     - "8081:8081"
  #   container_name: druid
  #   volumes:
  #     - druid_data:/opt/druid/var
  #   networks:
  #     - docker-net


  notebook:
    container_name: notebook
    build:
      context: ./notebook
    image: traffic-notebook:latest
    volumes:
      - ${PWD}/notebook/workplace:/home/jovyan/workplace
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-pass}
    # command: start-notebook.sh
    user: root
    env_file:
      - .env
    networks:
      - docker-net


  kafka-broker-1:
    image: bitnami/kafka:latest
    container_name: kafka-broker-1
    environment:
      # KRaft setting
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=clusterkafka
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-broker-1:9093,1@kafka-broker-2:9093
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-broker-1:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true # auto create topic
      # Listener
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9094,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-1:9094,EXTERNAL://kafka-broker-1:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Clustering
      # - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      # - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      # - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    ports: 
      - 9092:9092
      # - 9094:9094
    volumes:
      - kafka_data1:/bitnami/kafka
    networks:
      - docker-net
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10


  kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: kafka-ui
      networks:
        - docker-net
      depends_on: 
        - kafka-broker-1
      ports:
        - "7777:8080"
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_NAME=LocalKafka
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-1:9094
        # - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  # kafka-broker-2:
  #   image: bitnami/kafka:latest
  #   container_name: kafka_broker-2
  #   environment:
  #     # KRaft
  #     - KAFKA_CFG_NODE_ID=1
  #     - KAFKA_KRAFT_CLUSTER_ID=clusterkafka
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker 
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-2:9093,0@kafka-broker-1:9093
  #     # Listener
  #     - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9095
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-2:9092,EXTERNAL://localhost:9095
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
  #     # Clustering
  #     - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
  #     - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
  #     - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
  #   ports: 
  #     # - 9092:9092
  #     - 9095:9095
  #   volumes:
  #     - kafka_data2:/bitnami/kafka
    # networks:
    #   - docker-net
  #   healthcheck:
  #     test: nc -z localhost 9095 || exit -1
  #     start_period: 15s
  #     interval: 5s
  #     timeout: 10s
  #     retries: 10
